### ISSUE TITLE
After Delete Account, Recieve calls and messages

### ISSUE THREAD

**Issue by Rohnit** [BelledonneCommunications/linphone-iphone#100]
I have implemented code for logout functionality.

First I login check calls and messages. There is only one account there.
After Logout, There is zero account. Still there recieve calls and messages.

"public void deleteAccount(int n) {
		LinphoneAuthInfo authInfo = getAuthInfo(n);
		if (authInfo != null) {
			getLc().removeAuthInfo(authInfo);
		}
		
		LinphoneProxyConfig proxyCfg = getProxyConfig(n);
		if (proxyCfg != null)
			getLc().removeProxyConfig(proxyCfg);
		if (getLc().getProxyConfigList().length != 0) {
			resetDefaultProxyConfig();
		} else {
			getLc().setDefaultProxyConfig(null);
		}
		
		getLc().refreshRegisters();
                int len = getLc().getProxyConfigList().length;
		android.util.Log.e("LinPrfc","len " + len);
	}"

I checked at deleteAccount method in LinphonePreference class. After remove ProxyConfiguration, ProxyConfigList is zero. No What I do for prevent recieve calls and messages after delete account?

**Comment by bagage** [comment]
1. You must unregister from server with `linphone_proxy_config_edit(cfg); linphone_proxy_config_set_expires(0); linphone_proxy_config_done(cfg);` ** before removing the auth info **. 
2. This is linphone ios, not android hence closing this issue.

**Comment by alexiagonzalez** [comment]
Hi. Sorry, we know that this issue is closed, but could it be possible that it still occurs?

We use Linphone as base for our project. We've noticed that calls continue being received during a few minutes in our app after performing a logout ( = removing all accounts/proxies/authinfo, and following previous advices, etc) in certain circumstances. (We just only allow an account in our app)

We've detected that issue at Linphone app too... Is it really fixed? or is there any specific commit where the issue was resolved and which we can follow? 

Maybe the server (we use Freeswitch) should be who must unregister the user after a logout communication from app, cause the app couldn't do it?

Any help would be very appreciated. Thanks in advance, and very good work.
