### ISSUE TITLE
/bin/sh^M: bad interpreter - no such file or directory

### ISSUE THREAD

**Issue by mikeybeck** [BelledonneCommunications/linphone-iphone#103]
When I run make, I get the above error on the `/WORK/ios-x86_64/cmake/EP_vpx_configure.sh` and `/WORK/ios-x86_64/cmake/EP_ffmpeg_configure.sh` files.

I've tried running dos2unix on them but it doesn't seem to help.  
I can compile by using the flags `-DENABLE_FFMPEG=NO -DENABLE_VPX=NO -DENABLE_OPUS=OFF` but I don't want to do this.

Any suggestions?  (I'm using OSX)

(Sorry if this is a stupid question btw)

**Comment by bagage** [comment]
What's the error?

**Comment by mikeybeck** [comment]
Sorry I didn't make it very clear.  The error is `/bin/sh^M: bad interpreter - no such file or directory`

**Comment by bagage** [comment]
Strange, I never heard of such error earlier. Does command `sh` work on your machine?

**Comment by knoxcard** [comment]
Here is the answer, it was driving me nuts!  It is due to Windows file formatting and Linux file formatting.
This command clears out all the spaces and other crazy characters we probably do not even see.

$sed -i -e 's/\r$//' service.sh

(Reference)
http://halimdba.blogspot.com/2016/06/binshm-bad-interpreter-no-such-file-or.html

**Comment by ReisBenjamin** [comment]
Resolved

**Comment by hanhuizhu** [comment]
check sh file `:set  ff` is dos or nuix ,if is dos ,you need `set ff=nuix`
