### ISSUE TITLE
Not able to compile on Xcode 8 macOS Sierra 

### ISSUE THREAD

**Issue by TheEngineerz** [BelledonneCommunications/linphone-iphone#122]
@bagage I have followed each and every steps in readme file successfully . And after make command when I run the project in simulator it gives me 11 Errors. Kindly help me if any one have recently compiled it in Xcode 8 macOS Sierra .

Thanks

**Comment by juiced** [comment]
Please show us the errors you get.

**Comment by TheEngineerz** [comment]
@juiced Check this 
![screen shot 2016-10-12 at 9 26 05 pm](https://cloud.githubusercontent.com/assets/5149947/19318545/982e6d54-90c2-11e6-92e4-f83e03b9228e.png)

**Comment by TheEngineerz** [comment]
@juiced what you think ? I have done something wrong or there is really an issue .?

**Comment by TheEngineerz** [comment]
By Default iOS version 6 was selected and then i select the ios 8.3 from General Settings and issue was resolved . Thanks @juiced for participating : )

**Comment by juiced** [comment]
Ah, good to know, because I had no idea what was going wrong... :)

**Comment by luisvale** [comment]
can you guys help me? , Im also getting this errors 
![screen shot 2016-10-16 at 3 51 51 pm](https://cloud.githubusercontent.com/assets/4031895/19420468/dfae0154-93b9-11e6-813d-81bf62c774be.png)

and have no idea how to solve them.. the project didnt allow me to run because i needed xcode 8 so I made de upgrade and now getting these, if I comment those lines as they dont see much important (I just wanted it to run)  I get these:

![screen shot 2016-10-16 at 3 53 31 pm](https://cloud.githubusercontent.com/assets/4031895/19420483/1c819848-93ba-11e6-979e-e13a099969d0.png)
 please any help would be highly appreciated. 
thanks in advanced.

**Comment by TheEngineerz** [comment]
@luisvale have you complied the SDK successfully? i think you should not degrade the xcode 8. On Xcode 8 just complile the SDK successfully then open the project and from build setting change the deployment target to ios 8+. Also please check you project after Clean Building
