### ISSUE TITLE
Building SDK from 3.13.9 release

### ISSUE THREAD

**Issue by jelenadj** [BelledonneCommunications/linphone-iphone#126]
When I try to build SDK using code from 3.13.9, I am getting errors related with redefinition of CLOCK_... enumerators in belle_sip_utils.c, but when I try the same with master branch - everything works as expected (I am on macOS Sierra 10.12, iOS 10, Xcode 8).
I see this issue is fixed in belle_sip on Sept 13: https://github.com/BelledonneCommunications/belle-sip/commits/eaa198b1baffcae10246af71a6b70223f73eef7a/src/clock_gettime.c, but latest belle_sip release is marked on Aug 8, so this fix is not included and building linphone SDK using the latest linphone release 3.13.9 doesn't work.
Is it possible for you to make hot-fix release, adding just this fix in belle_sip, so we can use latest linphone-iphone release version for building SDK instead of using code from master branch?

**Comment by juiced** [comment]
Hi @jelenadj, what I did to solve sort of the same problems: I cloned the latest linphone version, compiled its linphone SDK and then copied the new liblinphone-sdk and submodules directory in place of the older linphone version. You will probably get some error messages when trying to compile linphone in Xcode, because some functions are a little different or added in the latest liblinphone-sdk which need to be (re)defined in the older linphone code. But no big deal and this way you have the latest linphone-sdk for the older linphone app version.
