### ISSUE TITLE
Unable to Compile LinPhone on Xcode 8 on MacOS serria 

### ISSUE THREAD

**Issue by araby123** [BelledonneCommunications/linphone-iphone#133]
Am trying to compile linphone for iphone but with no luck showing error for this code :

here :

 `size_t count = bctbx_list_size(linphone_core_get_proxy_config_list(LC));`
here:

`? bctbx_list_index(linphone_core_get_proxy_config_list(LC), linphone_core_get_default_proxy_config(LC))`

and here :

`LinphoneProxyConfig *proxy = bctbx_list_nth_data(linphone_core_get_proxy_config_list(LC),`

error :
`/Users/araby/Downloads/linphone-iphone-master/Classes/SideMenuTableView.m:105:24: Incompatible pointer types passing 'MSList *' (aka 'struct _MSList *') to parameter of type 'bctbx_list_t *' (aka 'struct _bctbx_list *')`

what happen and any idea to solve this so i can compile it ? i had 2 days searching with no luck at all

**Comment by araby123** [comment]
after i build the SDK also same issue remain

 `Incompatible pointer types passing 'MSList *' (aka 'struct _MSList *') to parameter of type 'bctbx_list_t *' (aka 'struct _bctbx_list *')`

**Comment by juiced** [comment]
Are you using the latest version of the linphone-iphone code from github?

**Comment by araby123** [comment]
Yup juiced  , from your git link in linphone.org website 

but after some trying and download "flexisip-master" and take this file from it (test - src ) i was able to compile it and run it in the simulator .  and running like a boss after that .  


now i trying to make my own SIP server from flexisip but also with no luck . can not register to my server at all .

**Comment by caferlop** [comment]
Hello there,

I´ve been trying to solve this problem for a while, but no luck. I´ve downloaded the latest SDK, and the latest pulls from the project, and still get the incompatible parameter type const MSList with bctbx_list_t error message when trying to compile. 

I´ve manage to make build and run it in simulator, when I just run it for the first time, and download the liblinphone by it´s own, but when I try to do it in a device, it miss all the libraries, and this happens because the libraries are only for i386, and miss arm64. If I add the latest SDK, the libraries  now are compatible with the standard architectures, but then I get the incompatibility parameter type error....

Is there any solution for it?
