### ISSUE TITLE
Cannot receive VoIP calls after moving from cellular to wifi

### ISSUE THREAD

**Issue by afriedmanGlacier** [BelledonneCommunications/linphone-iphone#136]
When the phone moves from wifi to cellular, the connection is briefly lost, but then re-registers and can receive SIP calls. When the phone moves from cellular to wifi, the connection is lost and does not come back up. User needs to manually touch the "registered" status to force it to re-register. 

I have seen this behavior a number of times, so in order to test I forced the issue by shutting off wifi on the phone, calling the phone, and then turning wifi back on and calling the phone.

**Comment by afriedmanGlacier** [comment]
Oops, there is one other variable I forgot to mention that could be causing the problem if others don't seen this issue. All of our VoIP calls are over OpenVPN. If others don't see this behavior, it is possible that the VPN is the issue going from cellular to wifi; however, I currently have no way to test without the VPN because of where our VoIP server is located.

**Comment by anatoli26** [comment]
Linphone over OpenVPN on iPhone has some pitfalls. As a rule of thumb, if Linphone is in foreground, it should re-register if OpenVPN tunnel drops and then is reestablished due to WiFi/cell networks changes (iOS 8 has a seamless tunnel option in OpenVPN).

If you're talking about background operation, you should not expect it working without push notifications. iOS turns off OpenVPN tunnel when in sleep mode, also on iOS 10 it's not allowed to have open TCP streams in background (for SIP over TCP). So the solution is to use PushKit. Linphone supports it if I'm not wrong, I'm planning to try it in a couple of weeks with Belledonne's Flexisip SIP server that has it natively.

The idea is to wake up the Linphone app with a push notification, so it tries to connect to the server for REGISTER and immediately receives there an INVITE for an incoming call. If OpenVPN is enabled (either intercepting all the traffic or just for the SIP server, or in on-demand mode), it'll be activated on re-registration so everything should work.

There's one issue I detected when using Linphone over OpenVPN tunnel when the tunnel is not for all the phone's traffic, but just for the SIP server. The RTP address specified by Linphone is incorrect: #135. Once it's solved, there should be no problems using Linphone over OpenVPN.

**Comment by afriedmanGlacier** [comment]
Anatoli,

Thanks for the response! It sounds like you are expecting the PUSH to
happen outside of the OpenVPN, correct? And then when the phone receives
the push notification, it will wake up and re-connect to the VPN in order
to receive the call? I'd love to hear how that works for you when you get
the chance to try it with Flexisip SIP server!

Thanks

**Comment by anatoli26** [comment]
@afriedmanGlacier, yes. Apple push always goes directly to the push servers, it never uses VPN tunnel. So, yes, the logic is as follows: first Linphone registers with PushKit-type push notification on a push-aware SIP server (like Flexisip). After some time, iPhone puts Linphone to sleep, turns off OpenVPN channel and only keeps a low-energy connection with the push servers.

When an incoming call is received at the SIP server, it sends a notification to the push servers, they deliver it to the phone and it just wakes the app up, so Linphone detects the connection to the SIP server is no longer active and tries to re-register.

Here, depending on your OpenVPN configuration, if it's an on-demand setup, iPhone sees that an app tries to connect to a OpenVPN-enabled destination, activates the VPN tunnel and there Linphone re-registers on the server and the server notifies it of an incoming call. And just there Linphone performs a user-visible action (like an incoming call notification).

By the way, the issue #135 I've mentioned before is fixed already in the latest version.

**Comment by ReisBenjamin** [comment]
Fixed

**Comment by afriedmanGlacier** [comment]
@ReisBenjamin, you said this is fixed, do you mean that when the phone moves from cellular to wifi, the connection will now re-register? Or do you mean that this whole question is now irrelevant because of PushKit and push notifications? (This distinction matters to me because we are currently using FreePBX which doesn't seem to have support for push notifications yet)

**Comment by ReisBenjamin** [comment]
@afriedmanGlacier Re-Registration has been added to the core of Linphone to be robust to network changes (for example loss of network or wifi to 4G etc...) so you should be fine.

**Comment by afriedmanGlacier** [comment]
@ReisBenjamin Awesome, thanks! Do you know when this was added? I have the latest Linphone from github as of the morning of Feb 24, a week ago. If it was more recent than that, I'll need to download again.

**Comment by ReisBenjamin** [comment]
@afriedmanGlacier You're version should be fine :)
