### ISSUE TITLE
How to use linphone over OpenVPN? How to enable Tunneling?

### ISSUE THREAD

**Issue by nitesh-borad** [BelledonneCommunications/linphone-iphone#142]

**Comment by anatoli26** [comment]
You can have a VPN tunnel to the SIP server established with the OpenVPN app and then register on the server with Linphone, specifying as server name the IP (or domain pointing to the IP) on the internal network.

You can have configured OpenVPN for on-demand connection specifying your SIP server address so every time Linphone needs to contact it, the connection is established. There's a reported problem however: #135 that prevents correct functioning over VPN tunnel when the OpenVPN is not intercepting all the traffic, but just the traffic to and from specific networks. The symptom of the problem is that the call is established but there's no audio.

**Comment by ReisBenjamin** [comment]
Answered
