### ISSUE TITLE
Video codecs: H.263,H.263plus - on Linphone iPhone

### ISSUE THREAD

**Issue by uditbatra** [BelledonneCommunications/linphone-iphone#17]
Hi,

How can these "Video codecs: H.263,H.263plus" be enabled on Linphone iPhone.

I was able to get H264 using below command:
./prepare.py -c && ./prepare.py --enable-non-free-codecs -DENABLE_OPENH264=ON all && make

Thanks

**Comment by uditbatra** [comment]
Please help me on this?

**Comment by bagage** [comment]
This is the same syntax:

 ./prepare.py -c && ./prepare.py --enable-non-free-codecs -DENABLE_H263=ON -DENABLE_H263P=ON all && make

**Comment by uditbatra** [comment]
Thanks, i will try

**Comment by uditbatra** [comment]
I tried with the above command. It build successfully.

What will be step to enable H263 in App.
What all changes in LinphoneIphone code do i have to make to use it.

Thanks

**Comment by uditbatra** [comment]
It worked.Thanks

**Comment by sree127** [comment]
Hi @uditbatra @bagage 

I'm not able to install the H263 library even after running the above command. Can you guys please have a look at [](https://github.com/BelledonneCommunications/linphone-iphone/issues/154) and help me out.

Thanks a ton

**Comment by babumoshai-ankush** [comment]
Hi @sree127 ,

Look into the **codec_pref_table** array in LinphoneManager.m. Debug **+ (NSString *)getPreferenceForCodec:(const char *)name withRate:(int)rate** function. You may able to understand everything. 
In that aforesaid function you can find your codec strings are coming as name(like H263-1998, H263 etc) which are added in the at the time of building sdk with `$./prepare.py - && ./prepare.py [options] && make`. But cannot match, because of **H263-1998** and **H263** etc codec values are not present in the array **codec_pref_table**.

You can add those code values in that array like -
```
...
{"H263-1998", 90000, "h263_preference"},
{"H263", 90000, "h263p_preference"}
...
```

Regards,
Ankush Chakraborty

**Comment by babumoshai-ankush** [comment]
@uditbatra  where I have to  add those lines? Can you help please? I'm trying to add H263 codec but failing. In the codec list its not shoing Settings-->Video. Also make the SDK with the options. That is also not work for me

`$ ./prepare.py -c && ./prepare.py -DENABLE_H263=ON -DENABLE_H263P=ON -DENABLE_MPEG4=ON -DENABLE_FFMPEG=ON -DENABLE_NON_FREE_CODECS=ON && make`

```
linphone_core_enable_payload_type(theLinphoneCore, linphone_core_find_payload_type(theLinphoneCore, "H263-1998", 90000, -1), TRUE);
linphone_core_enable_payload_type(theLinphoneCore, linphone_core_find_payload_type(theLinphoneCore, "H263", 90000, -1), TRUE);
```

**Comment by vishwas00** [comment]
Use below command to enable H264 codec-

./prepare.py -c && ./prepare.py -DENABLE_NON_FREE_CODECS=ON -DENABLE_OPENH264=ON && make
