### ISSUE TITLE
Bug link your account

### ISSUE THREAD

**Issue by p5panam** [BelledonneCommunications/linphone-iphone#173]
There is a new feature called LINK YOUR ACCOUNT.
I use another sip account different from linphone.org on the Assistant Configuration (Use sip account), and the software is always asking and showing to "Link your linphone.org account XXXX" alert when executed.

Please remove this from the software as it is useless and even complicate end user in case he dont use linphone.org sip server

**Comment by ReisBenjamin** [comment]
Fixed in commit 9b57a315647f92bce6cf4b0b30f221af1e2c6376

**Comment by schultzter** [comment]
I've tried linking my linphone account to my phone number, and I received the four digit validation code but after I entered it and tapped the Activate button nothing happens and I can't even back out - I have to kill the Linphone app and re-open it. The same thing happens when I try to link the SIP account from my VoIP provider to my phone number. 

It also gets stuck on the Choose a country screen, I can't choose the country and I pressing the back arrow at the top left or the back button on my phone doesn't do anything!?

Samsung Galaxy S8 running Android 9 and Linphone v.4.1.1
