### ISSUE TITLE
CallKit sometimes fail to hangup call

### ISSUE THREAD

**Issue by henrik415** [BelledonneCommunications/linphone-iphone#187]
Hello.

I've integrated CallKit into my own app. For the most part everything works as intended except for one thing. Sometimes iOS fails to register that my VoIP call is terminated and continues to show the green bar at the top of the screen. 

I've checked and I'm calling `reportCallWithUUID: endedAtDate:nil reason:` whenever LinphoneCore informs me that a call is ended. The CallKit UUID are matching up but still iOS insists that there is a call.

Has anyone else seen this?

**Comment by hmaracic** [comment]
Hi,
You say you integrated it into your own application. Have you maybe used the same way to register a CallKit call with the system as Linphone?
Because that way may cause multiple registrations for outgoing calls.
While you're still in a call lock the phone (turn on speaker first so your call doesn't get disconnected) and check to see how many outgoing calls CallKit is showing. If it's more than one, that's your problem.
This has been reported in #182 and the fix has been introduced in #183 which still hasn't been merged into the Linphone code base.

**Comment by henrik415** [comment]
Hi
I'm not using any of the UI code from Belledonne so your fix in #182 is not directly applicable to my code. From my traces it doesn't look like I'm registering more than one call in the CallKit framework.

But it's good to know that you got it working, that suggest that it's something in my code that needs fixing. I'm just having a hard time reproducing.
I'll keep debugging.

**Comment by ReisBenjamin** [comment]
Not related to this git repo

**Comment by bhoomik** [comment]
@henrik415  Have you found solution for this?
