### ISSUE TITLE
603 does not trigger LinphoneCallError state?

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#261]
Hi. I'm currently using linphone lib 3.16.4 from linphone official website, and I found that I can't catch 603 decline in LinphoneCallError state anymore.

Call state changes when callee declines with 486 busy here:
LinphoneCallOutgoingRinging -> LinphoneCallError(486) -> LinphoneCallRelease

Call state changes when callee declines with 603 decline:
LinphoneCallOutgoingRinging -> LinphoneCallEnd -> LinphoneCallRelease

is it meant to be like this or a bug?  is 603 not considered as an error code anymore?
If so, I really think this is a bad design especially when I need to prompt a dialog on 603 as well as 486.

Thank you in advance for any response.

**Comment by ReisBenjamin** [comment]
Hello,

This is the normal behavior since it's not an error to decline a call. (all non 4xx code are not error)
You can check the error info to see which code you received : 

const LinphoneErrorInfo *ei = linphone_call_get_error_info(call);
if (ei) int code = linphone_error_info_get_protocol_code(ei);

This way you can get the 603 of the decline and process the call as you wish.

Regards,
Benjamin
