### ISSUE TITLE
Linphone starts re-registering to Freeswitch every time it is brought to foreground

### ISSUE THREAD

**Issue by chitkosarvesh** [BelledonneCommunications/linphone-iphone#271]
Hi,
I have been working on the code for some time and it has been a breeze except for figuring out this issue:
Whenever the app is put in the background, and then bought to the foreground, it begins to register without acknowledging the connection made previously.
What I want to achieve is to unregister the current connection and then start the registration.
Can anyone point me in the right direction? Or, is there a workaround?
Thanks

**Comment by ReisBenjamin** [comment]
Hello,
Because of IOS10 background policy, VoIP sockets are closed whenever the app goes in background therefore the connection to the server is no longer correct so you need to re-register when the app is in foreground to recreate a correct connection.

**Comment by ReisBenjamin** [comment]
Nothing's to be done

**Comment by bnsy** [comment]
Hello @ghost

My app sends a register request every time I open the app after termination.

Due to this multiple entries are created in the VOIP server. Attaching a screenshot for your reference.

Please have a look and let me know if anything is.

(https://user-images.githubusercontent.com/35221271/176193727-372bdc2d-ea55-4247-b8df-1ac8e5dc0024.png)
