### ISSUE TITLE
the app de-registers when phone goes to sleep after 2~3 minutes. 

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-iphone#287]
the app goes to background mode and does not receive a phone call after it goes to sleep between 2 to 3 minutes. I have to open the app again and then it registers and receives calls, however once I open another app and keeping the linphone app open in the background it de-registers again in 2 to 3 minutes. is there a fix for this ?

**Comment by ReisBenjamin** [comment]
Do you see an de-registration in the logs ?
Since ios10 all voip sockets are closed when an app goes in background that's why it can't receives anything.
You'll need to use push notifications sent by the server i order to wake the app up. Once the app is awaken it registers to the server and can receive calls and messages.
you can look at PushKit Apple Framework documentation.
Push notification are already implemented in Linphone so you just need to make sure there are enabled in your account settings and that your server supports sending them.

Regards

**Comment by S0U1SB4N3** [comment]
Yes I see it de-register in the sip logs on server

**Comment by ReisBenjamin** [comment]
Can I see logs when the issue happens ?

**Comment by S0U1SB4N3** [comment]
The incoming call UI doesn't show up just the background iOS call from background screen. Is there a reason it goes to background mode almost immediately ... I'll send you screen shots in my next reply thank you for any assistance

**Comment by ReisBenjamin** [comment]
Hello,

I don't understand your last message.
Can you show logs of unregistration ?
In order to display a new incoming call when app is in background or killed you'll need CallKit or a Notification after the app is awaken by PushKit.

What do you mean by "Is there a reason it goes to background mode almost immediately ..." ?
The app doesn't go in background alone it's either you or the system that put it in background.

Regards

**Comment by S0U1SB4N3** [comment]
I have the AppStore app open 
And I call the sip number 
And I'm sending you screen shots 
![Image](http://i.imgur.com/wis7veP.jpg)
This is the home screen I get when I call it notice the arrow on bottom left then a few milliseconds later this is the screen I get 
![Image](http://i.imgur.com/2CbID1B.jpg)
This is the background mode screen 
While the app is active and open 
Please don't talk down to me. I'm a developer might not be advanced in voile like you but I can give you a solid test of your app and report the bug properly 
I'm using this as a standard user would and I apologize if this offended you but I'm just trying to get this resolved as it's happens the same way on my multiple friends iOS iPhone ,6s plus and 7 and 7splus this just started about a few weeks ago ... did Apple change anything I'm not aware of and now the. Background handler is bad ?

**Comment by S0U1SB4N3** [comment]
the android version is stable and works great

**Comment by S0U1SB4N3** [comment]
I got the VoIP push to wake up the app in my test build from your source code but the background mode is active while the app is active on your iTunes release

**Comment by S0U1SB4N3** [comment]
On this display 
![Image](http://i.imgur.com/btxztpu.jpg)
How do I change it to show the phone number instead of name with the app name ? If you don't mind answering a remedial question.

**Comment by ReisBenjamin** [comment]
Hello,

I had no intention to talk down to you and I don't think I did, I genuinely didn't understant what you were saying and here i am still trying to help you.

About the screen shot : this not a screen as the app goes in background it's the CallKit UI to display an incoming call (just like for a GSM call), in order for CallKit to work properly it requires to always manage calls (not only when the app is in background) that's why you'll see this screen even with the app in foreground.

As for the number not being displayed this is indeed anormal, i'd need logs of the incoming call to see why it doesn't find your number.
Is this number in your Address Book ?

It's impossible not to display the app name but you can change the text above if you want : 
update.remoteHandle = **[[CXHandle alloc] initWithType:CXHandleTypeGeneric value:handle];**
where handle is a string that you want to display.
You can change the call to this function in **ProviderDelegate.m** methd **reportIncomingCallwithUUID:(NSUUID *)uuid handle:(NSString *)handle video:(BOOL)video**

**Comment by S0U1SB4N3** [comment]
thank you for clearing this up I will provide the logs when they become available. 
the only reason i thought this was the background mode screen is that Bria displays the same notification in the same way when its on the lock screen 

I get this message with the linphone app active foreground and when its on the lock screen both and only on the lock screen in Bria

**Comment by S0U1SB4N3** [comment]
the push notification was fixed when I send the push notification to the linphone immediately before I send the call doing so from the server. it did wake the phone app up enough to register right before it got the call. but I get the screen above regardless if I'm in lock screen or not. whether the phone number is in my address book or not.

**Comment by ReisBenjamin** [comment]
Okay, Bria probaly decided to only show CallKit UI when in background but in order to have better interraction with GSM calls it's preferable to have called managed by callkit, that's why we chose to always displayed it.

As i said the text displayed above Linphone audio is managed by the remoteHande (see my previous post) you need to find why it's always the same text that is displayed.
Normally it should display your contacts name if it's one of your address book contact, if not then the display name of the address or the username if there's no display name.

Regards

**Comment by S0U1SB4N3** [comment]
thank you for this its a big help. and thank you for doing a good job with the code on the linphone project. keep it up :)

I named that extension network operation in my sip server 

on a cell phone call it it just said New York, NY or Cellphone when I called from my cell phone 
the name needed to show the number of the caller id not the name of the caller ID  like my friend Brandon called and I don't have him in my address book but it still shows his name from the carriers caller ID see next picture

**Comment by S0U1SB4N3** [comment]
![Image](http://i.imgur.com/uSYq9gK.jpg)

**Comment by ReisBenjamin** [comment]
It's probably because Brandon has a display name in his invite. What you want to do is display the username of the address instead of the display name.

**Comment by S0U1SB4N3** [comment]
sip-uri correct

**Comment by S0U1SB4N3** [comment]
[Debug] (  PhoneMainView.m:756 ) Battery state:2 level:0.98
2017-08-21 11:57:51.693580-0500 smartphone[357:18587] [Message] Background task belle-sip recv channel started. Unknown remaining time since application is not fully in background.
2017-08-21 11:57:51.693963-0500 smartphone[357:18587] [Message] channel [0x1047b4000]: starting recv background task with id=[42].

**Comment by S0U1SB4N3** [comment]
I've tried a few things and can not get the sip address to form it freezes the application unless I keep it value:handle or if I change the value to value:@"Anything I want to type" 

sorry to bother you again.

**Comment by S0U1SB4N3** [comment]
how do I display the user name ? instead of the display name ?

**Comment by S0U1SB4N3** [comment]
char *uri = linphone_address_as_string_uri_only(addr);
 no luck yet ;/

**Comment by S0U1SB4N3** [comment]
linphone_call_get_remote_address(call) still no luck with this one either

**Comment by S0U1SB4N3** [comment]
CXHandleTypePhoneNumber still displays caller name not number.. any help would be appreciated

**Comment by S0U1SB4N3** [comment]
ok I've ran a script to manually remove all the alpha characters from handle and there was nothing left. 
my incoming call logs 

Linphone core [0x102060200] notified [call_state_changed]
[633:82677] [Message] Contact has been fixed using proxy
[633:82677] [Message] channel [0x105e4c000]: message sent to [TCP://(ip deleted):5060], size: [437] bytes
[633:82677] [Message] 	SIP/2.0 180 Ringing
[633:82677] [Message] 	Via: SIP/2.0/TCP (ipDeleted):5060;branch=z9hG4bK61091aa8;rport
[633:82677] [Message] 	From: "Network Operations" <sip:0000@(ipDeleted)>;tag=as731e3bd8
[633:82677] [Message] 	To: <sip:office-6015@(ipdeleted):51753;transport=tcp>;tag=CkZ2xDe
[633:82677] [Message] 	Call-ID: 1ba119013472e80624260cc6308f61b6@(Ipdeleted):5060
[Message] 	CSeq: 102 INVITE
[633:82677] [Message] 	User-Agent: LinPhone._iPhone.6s.Plus_iOS10.3.3/b531f682 (belle-sip/1.6.1)
[633:82677] [Message] 	Supported: replaces, outbound
[633:82677] [Message] 	Content-Length: 0
[633:82677] [Message] Dialog [0x1705c0f00]: now updated by transaction [0x170778540].
[633:82677] [Message] channel [0x105e4c000]: ending recv background task with id=[36].

I think the value:handle is just grabbing the From: "Network Operations" <sip:0000@(ipDeleted) name and not the number. I would really like to simply the sip address instead of the name "sip:number@domain"

**Comment by ReisBenjamin** [comment]
I saw you have open another issue, so i'll close this one and we'll continue on the new one.

Regards

**Comment by S0U1SB4N3** [comment]
Incoming calls exit after 32 seconds when push is active

**Comment by ReisBenjamin** [comment]
I need to see logs of a call in order to find what happens.
32s is the default timeout if the ACK of the 200OK is not received.

**Comment by S0U1SB4N3** [comment]
the ACK missing issue was due to character limits in asterisk char(255)
I had to strip out some of the data that was being sent to under or at the character limit (255) and it is now resolved.  you can close this, thank you

**Comment by S0U1SB4N3** [comment]
sorry this was the string modification 
NSString *params = [NSString
			stringWithFormat:@"app-id=%@%@.%@;pn-type=apple;pn-tok=%@;"
							 @"%@%@",
							 [[NSBundle mainBundle] bundleIdentifier], notif_type, APPMODE_SUFFIX, tokenString, timeout, silent];

linphone manager.m 
for asterisk, hope this helps others :)
