### ISSUE TITLE
Call state changed error

### ISSUE THREAD

**Issue by Maleandr** [BelledonneCommunications/linphone-iphone#324]
Hi,

My app is crashing (EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000) on linphone core method - linphone_core_notify_call_state_changed (line number 64). It happens only with call state released.

Somehow my callbacks methods are not referenced in linphone core. I don't understand how is this possible. My best guess is that I'm calling linphone_core_unref before all callbacks are finished. How I can wait before all callbacks are finished? I'm using linphone_core_get_calls_nb, but this probably doesn't work for calls in released transition.

**Comment by ReisBenjamin** [comment]
Hello,

indeed when released a call is not count in linphone_core_get_calls_nb.
in order to reference your callback in the core you can do : 
linphone_core_cbs_set_call_state_changed(LinphoneCoreCbs *cbs, LinphoneCoreCbsCallStateChangedCb cb); as shown in the LinphoneManager createLinphoneCore method.

**Comment by Maleandr** [comment]
Sorry for spam. I found my problem. Basically I was calling liphone_core_unref in core iterate loop, which caused this problem. Dispatch.main.async fixed it.

**Comment by ReisBenjamin** [comment]
OKay, i'll close the issue then.

Best regards
