### ISSUE TITLE
MISSING CALL FEATURE - intended transfer 

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-iphone#334]
im need in to do a transfer button that does a warm transfer not a blind transfer to an extension.

**Comment by ReisBenjamin** [comment]
Hello,

I don't know what means warm transfer and blind transfer, can you explain ?

Thanks

**Comment by S0U1SB4N3** [comment]
Ok blind transfer is set up in the program already. You dial the extension and hit transfer button and it hangs up on you and transfers your call to the dialed extension ...

Warm transfer 
You are on a call and you want to call another extension talk to that person then transfer the call to that person and hang up your call.

**Comment by ReisBenjamin** [comment]
Hello,

The warm transfer is indeed not used in Linphone iOS but you can use it if you want to because liblinphone supports it as you can see in call.h : 
/**
 * Performs a simple call transfer to the specified destination.
 * The remote endpoint is expected to issue a new call to the specified destination.
 * The current call remains active and thus can be later paused or terminated.
 * It is possible to follow the progress of the transfer provided that transferee sends notification about it.
 * In this case, the transfer_state_changed callback of the #LinphoneCoreVTable is invoked to notify of the state of the new call at the other party.
 * The notified states are #LinphoneCallOutgoingInit , #LinphoneCallOutgoingProgress, #LinphoneCallOutgoingRinging and #LinphoneCallConnected.
 * @param[in] call The call to be transfered
 * @param[in] refer_to The destination the call is to be refered to
 * @return 0 on success, -1 on failure
**/
LINPHONE_PUBLIC LinphoneStatus linphone_call_transfer(LinphoneCall *call, const char *refer_to);

/**
 * Transfers a call to destination of another running call. This is used for "attended transfer" scenarios.
 * The transfered call is supposed to be in paused state, so that it is able to accept the transfer immediately.
 * The destination call is a call previously established to introduce the transfered person.
 * This method will send a transfer request to the transfered person. The phone of the transfered is then
 * expected to automatically call to the destination of the transfer. The receiver of the transfer will then automatically
 * close the call with us (the 'dest' call).
 * It is possible to follow the progress of the transfer provided that transferee sends notification about it.
 * In this case, the transfer_state_changed callback of the #LinphoneCoreVTable is invoked to notify of the state of the new call at the other party.
 * The notified states are #LinphoneCallOutgoingInit , #LinphoneCallOutgoingProgress, #LinphoneCallOutgoingRinging and #LinphoneCallConnected.
 * @param[in] call A running call you want to transfer
 * @param[in] dest A running call whose remote person will receive the transfer
 * @return 0 on success, -1 on failure
**/
LINPHONE_PUBLIC LinphoneStatus linphone_call_transfer_to_another(LinphoneCall *call, LinphoneCall *dest);

linphone_call_transfer -> blind transfer
linphone_call_transfer_to_another -> warm transfer

**Comment by tabitabe** [comment]
Hi Reis,

Would this be the same for Android?

**Comment by mounikakrify** [comment]
hi ReisBenjamin,

LINPHONE_PUBLIC LinphoneStatus linphone_call_transfer_to_another(LinphoneCall *call, LinphoneCall *dest)
we are failed get destination address and flow to use this method.

**Comment by srkreddykrify** [comment]
Hi Reis,
is warm transfer possible in Android . please guide  me
