### ISSUE TITLE
No timeout for registration?

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#350]
Is there a timeout counting when the register server is not responding?
When I try to register to 123@127.0.0.1 (doesn't exist) it keeps sending register message every 4 secs infinitely. How can I make it return LinphoneReasonIOError after a certain period like the old times? 
is there an option to set the timeout counter programmatically?😥

Thank you.

**Comment by ReisBenjamin** [comment]
Hello,

Linphone only displays a Registration Failed if the server responds a 4XX (403 forbidden for example)
if there's no response he'll retry indefinitely because the goal is to be registered as often as possible.
The time-out registration has never been implemented in linphone nor will it be because it's impossible to differentiate a server that doesn't exist from a server unreachable for network reasons.

Best regards
