### ISSUE TITLE
Push notification or Pushkit is not working

### ISSUE THREAD

**Issue by Skkumawat** [BelledonneCommunications/linphone-iphone#355]
Hello,

I had successfully setup the Linphone library and tried to test push notification when app is in background or kill.

I have also replace the "rootca.pem" for development and prod. but I'm not getting any type of push on device for receiving a call.

Please provide me a solution for this issue.

**Comment by ReisBenjamin** [comment]
Make sure push notification settings is turned on in your account settings and that your server supports sending push notifications.

**Comment by Skkumawat** [comment]
I have already turned on push settings.

**Comment by ReisBenjamin** [comment]
Then does your sip service supports sending push notifications ?

**Comment by S0U1SB4N3** [comment]
PUSH works with call kit apple changed this in the USA, you need to ensure your packaging your app with the voip certificate too or it will not function, I had to tweak what was sent to my asterisk server so that wit would not hang up after 30 seconds due to keep alive errors. its all server side changes for the most part not this program. you will also need to make a file that adjusts how many seconds to wait before sending the awake token then the call its self from asterisk. 



 hope this helps clear this up. as of apple iOS 10.13 push kit is only for non-void transmissions and push kit is for notifications, also due to using call kit the incoming calls will look like regular cellular incoming calls it does not use the linphone software interface for incoming calls initially with iOS due to apples changes.

**Comment by Skkumawat** [comment]
Okay, Thanks for your response.

I have integrated Callkit and push kit for push notification. but still I'm not getting any type of push on device.

I'm some confused that where to upload .pem file of push and VOIP. According to Linphone library we have to replace .pem file to our developer push certificate. but not getting push when we receive a call in background mode or app kill.

Please suggest what am i missing?

**Comment by ReisBenjamin** [comment]
Hello,

The server should also have a certificate for sending Apple push notifications.
The certificate of Linphone & flexisip only supports sip.linphone.org accounts.

**Comment by S0U1SB4N3** [comment]
yes SKK... that is correct you manually configure the push cert on your apple developer account and associate it with your build identifier, hope that helps

**Comment by Trushangpatel** [comment]
Hello,

I will resolve this issue from voip silent push notification.
if you need help then mail me: trushangpatel3993@gmail.com, add subject: linphone issue

Thanks
