### ISSUE TITLE
losing linphonerc config file when receiving push during lock screen on first boot

### ISSUE THREAD

**Issue by lucifer662607004** [BelledonneCommunications/linphone-iphone#371]
I encounter this problem in my own app, which is built from linphonecore lib.

When I receive VoIP push from Apple, I will try to send REGISTER by using linphone_core_refresh_registers();
But when I do this during lock screen shown on iPhone first booting up(particularly the one that you can not unlock it with fingerprint or face), the linphonerc file will be erased, in which case sip accounts and settings are all gone.

I think it triggers apple file protection mechanism:
https://developer.apple.com/documentation/foundation/nsfileprotectioncomplete
Apps is not allowed to read and write files in document path by default, until users unlock it from first booting up.

I have to disable this feature to fix the problem:
NSDictionary *attribute = [NSDictionary dictionaryWithObject:NSFileProtectionNone forKey:NSFileProtectionKey];
[[NSFileManager defaultManager] setAttributes:attribute ofItemAtPath:linphonercPath error:&error];

But sometimes it doesn't work, it seems linphonerc is removed and rebuilt in somewhere and re-enable the protection.

How is linphone dealing with it? Appreciate any help.

**Comment by zj299792458** [comment]
Every time I set it as NSFileProtectionNone, it will go back to NSFileProtectionCompleteUntilFirstUserAuthentication at next startup.

**Comment by ReisBenjamin** [comment]
You can look how we process a push notification in processRemoteNotification method in LinphoneAppDelegate.m

**Comment by zj299792458** [comment]
@ReisBenjamin Hi, appreciate the responds. 

I've read the code. if I understand it correctly, processRemoteNotification is just trying to make some background time...

I'm wondering if Linphone had been killed in the multi-task list(double click home button), can it still ring when it's restarted by a VoIP call push? If the SIP port is random I don't think it can still receive the call through SIP without re-registration, there should be a NAT issue. 

Thank you

**Comment by ReisBenjamin** [comment]
Hello,
indeed you're right,
The push notification is only used to wake the app up (event if double click home button killed) so that it registers and then once registered receives the call

**Comment by zj299792458** [comment]
@ReisBenjamin 

If so, do you mind to run a test? since I don't have Linphone push certificate.

steps:
1. make sure latest iOS version installed (11.2.5 by now).
2. make sure the phone have a 4G/3G network connection and do NOT have SIM PIN(it's important).
3. register an account on Linphone, and power off the phone.
4. power back on, until you see the lock screen with password (make sure it have password).
5. DO NOT unlock the screen (if you do please power off again). The phone will be in BeforeFirstUserAuth state. (only 4G/3G data works on this state)
6. make a VoIP push by calling Linphone or any other way. Wait for a few seconds make sure Linphone have been woke by push. 
7. UNLOCK THE LOCK SCREEN, enter Linphone. If you didn't see the loading screen, it should be successfully woke previously. (If not plz check the steps)
8. Is everything ok? is the account still there? (it doesn't matter if you use a internal IP that can't receive a call on cellular network)

Thank you.
