### ISSUE TITLE
iOS when device is locked not getting calls

### ISSUE THREAD

**Issue by krishnastvSMSC** [BelledonneCommunications/linphone-iphone#532]
Hello Team,

We changed Transport to TCP, and set the start_at_boot_preference to YES. Immediate app locks we are getting call, after some time not getting any calls. How to resolve this issue. Any response will be good.

Thanks

**Comment by Trushangpatel** [comment]
Hello,

I will resolve this issue from voip silent push notification.
if you need help then mail me: trushangpatel3993@gmail.com, add subject: linphone issue

Thanks

**Comment by cimm** [comment]
I am having the same problem. Quick summary of what I've learned so far.

Since some recent version of iOS applications are no longer allowed to run in the background after some time. iOS kills the application. It doesn't matter if the application is using UDP, TCP or TLS connections. 

You can test this by calling your SIP number when Linphone runs in the foreground and the phone is unlocked. Lock the phone and the phone will no longer ring (after a few minutes maybe, not sure about the timing). It works fine on Android since Android allows to run background applications. iOS does this to preserve battery life.

This can be fixed by sending an iOS push notification (via APNS) to the application right before the call comes in. This wakes the application (only when there is something to do, so good for battery life), and Linphone will be able to receive the incoming call. All good. I think that's how the standard Linphone account does it.

Now, we are using our own SIP system (Twilio) meaning you can't wake up an application you don't compile yourself. You can't only send a push notification to you "own" (meaning apps you published on the app store) apps as far as I know. This is annoying since it means we can't send a push notification to the standard Linphone app, even if we wanted to. We would have to compile and publish Linphone ourselves.

[Prowl](https://www.prowlapp.com/) has a system where I can send it an HTTP request and it will send a push notification to the phone. Something like that would be awesome.

Does anyone have a way to tell the App Store version of Linphone to wake up?

**Comment by aminsaeedmehr** [comment]
its an old topic and was searching for the same problem here in 2020, the problem just solved by replacing GSWAVE softphone
it rings even if the phone is locked after hours. we are using and have no problem so far (3 months has passed)
