### ISSUE TITLE
Development Archive error: Bundle only contains bitcode-marker

### ISSUE THREAD

**Issue by yuehengwu** [BelledonneCommunications/linphone-iphone#567]
When I archive by development or adhoc, it occur some errors , but archive by AppStore success.
I use linphone 4.2 sdk.

Here is error message : 
`Failed to verify bitcode in mediastreamer2.framework/mediastreamer2:
error: Bundle only contains bitcode-marker /var/folders/v0/10nxz_q55n134dzphh8l0gs00000gn/T/IDEDistributionOptionThinning.mXe/Payload/AJSipManager_Example.app/Frameworks/mediastreamer2.framework/mediastreamer2 (arm64)`

But I already set bitcode to `NO` in project setting, and add a run script to build phase .

**Comment by shdaro** [comment]
I also got the same error while archiving for adhoc.

`Failed to verify bitcode in bctoolbox-tester.framework/bctoolbox-tester: 
error: Bundle only contains bitcode-marker /var/folders/9z/rcrg8_3d3g51033gxmsmxhkw0000gn/T/IDEDistributionOptionThinning.YMS/Payload/linphone.app/Frameworks/bctoolbox-tester.framework/bctoolbox-tester (armv7)`

My bitcode also set to no.

=========================================

 When I set bitcode to yes then the build faild saying that `linker command failed with exit code 1 (use -v to see invocation)`

`ld: bitcode bundle could not be generated because '/Users/apple/Public/linphone-iphone/Pods/linphone-sdk/linphone-sdk/apple-darwin/Frameworks/bctoolbox.framework/bctoolbox' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/apple/Public/linphone-iphone/Pods/linphone-sdk/linphone-sdk/apple-darwin/Frameworks/bctoolbox.framework/bctoolbox' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)`


Hope someone great soul will help.
