### ISSUE TITLE
Call Drops when receiving the Push calls some times

### ISSUE THREAD

**Issue by pasha4uu** [BelledonneCommunications/linphone-iphone#653]
Hi , 

I cloned new master branch, builded it successfully. in this build, all incoming and out going calls are working well. and also are working push (VOIP) calls.

 -----> my issue is----:

  but when i'm receiving the push call some times drops the call. It means 
 when I lift the call it will be declined at some secs or less than 2 mins. 

 what is the issue? 
 please give any solution ..  
would be any help I really more appreciate.

**Comment by balusreekanth** [comment]
I think once push notification awake the app and call connects  PN job is done . Now It is all about RTP and SIP headers . Check if you have media issues or any NAT issues . Better take packet trace and check the reason for call drop.

By the way , can you please share more details how you achieved push notifications working for IOS . Please share scripts  and  in detailed . I have issue with PN . Using asterisk

**Comment by harsukhbir** [comment]
I am facing an issue in  iOS which user is on first incoming  call and then receives an other incoming call. Then I tried to disconnect the call by giving the reason busy by using the Linphone method. But this method declines my both calls the one which I received and the other one which is incoming. Can anyone suggest that how can I disconnect the single call. Because SDK deoes not provide me any callback or state for disconnecting particular one call.
if (linphone_core_get_calls_nb(LC) > 1) {
            
                   linphone_call_decline(call, LinphoneReasonBusy);
             
               return;
        }

**Comment by impingebaljit** [comment]
I am facing an issue in which user is on first incoming  call and then receives an other incoming call. Then I tried to disconnect the call by giving the reason busy by using the Linphone method. But this method declines my both calls the one which I received and the other one which is incoming. Can anyone suggest that how can I disconnect the single call. Because SDK deoes not provide me any callback or state for disconnecting particular one call.
if (linphone_core_get_calls_nb(LC) > 1) 
{
  linphone_call_decline(call, LinphoneReasonBusy);
    return;
  }
