### ISSUE TITLE
Linphone push calls not working when app is the closed (some scenario"s)

### ISSUE THREAD

**Issue by pasha4uu** [BelledonneCommunications/linphone-iphone#665]
Hi I cloned the project from master Branch and run the build successfully. I’m using latest Xcode and iOS 13.6
In this build VOIP calls working fine (when app is the closed)

This scenario VOIP calls are working fine .(when app is the closed) :--
1.When getting the incoming call and lifted and went to call screen.(this scenario works perfectly )

This scenarios VOIP calls are not working .(when app is the closed) :--
1, when getting the incoming call if your not lifted the call (after that  making a call again we are not getting the call)
2. When the caller disconnect the call(after that  making a call again we are not getting the call)

so please tell what was the reason ? Why I’m unable to receive the call ?
have anybody facing this issue ?
please help and give any solution

Would be any help really appreciate

**Comment by brightson93** [comment]
to be frank, I even have problem understanding your explanation of the issue. maybe you can elaborate more with simple english?

**Comment by pasha4uu** [comment]
Hi @brightson93  content updated please read again

**Comment by pasha4uu** [comment]
crash logs :----


EXCEPTION NAME:NSInternalInconsistencyException ---> EXCEPTION NAME:Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.  --->CRASHSYMBOLS : (\n\t0   CoreFoundation                      0x00000001b5234668 E2D6A76B-6879-31A3-8168-DF49F94E17CD   1222248\n\t1   libobjc.A.dylib                     0x00000001b4f56bcc objc_exception_throw   56\n\t2   CoreFoundation                      0x00000001b51376ec E2D6A76B-6879-31A3-8168-DF49F94E17CD   186092\n\t3   Foundation                          0x00000001b557d16c EEBCBA18-269A-351C-BCE0-D23E156923D4   553324\n\t4   PushKit                             0x00000001c9424ab8 A87C7189-6C76-39AB-B9B3-40960C15430D   19128\n\t5   libdispatch.dylib                   0x00000001b4efa524 361DA09A-E7CE-30EB-8DFC-9D9AF9DE4A0A   374052\n\t6   libdispatch.dylib                   0x00000001b4ead0b0 361DA09A-E7CE-30EB-8DFC-9D9AF9DE4A0A   57520\n\t7   PushKit                             0x00000001c9423a70 A87C7189-6C76-39AB-B9B3-40960C15430D   14960\n\t8   libdispatch.dylib                   0x00000001b4ef99a8 361DA09A-E7CE-30EB-8DFC-9D9AF9DE4A0A   371112\n\t9   libdispatch.dylib                   0x00000001b4efa524 361DA09A-E7CE-30EB-8DFC-9D9AF9DE4A0A   374052\n\t10  libdispatch.dylib                   0x00000001b4eac5b4 361DA09A-E7CE-30EB-8DFC-9D9AF9DE4A0A   54708\n\t11  CoreFoundation                      0x00000001b51b26bc E2D6A76B-6879-31A3-8168-DF49F94E17CD   689852\n\t12  CoreFoundation                      0x00000001b51ad590 E2D6A76B-6879-31A3-8168-DF49F94E17CD   669072\n\t13  CoreFoundation                      0x00000001b51acba8 CFRunLoopRunSpecific   424\n\t14  GraphicsServices                    0x00000001bf31c344 GSEventRunModal   160\n\t15  UIKitCore                           0x00000001b92e83e4 UIApplicationMain   1932\n\t16  ALinphone                           0x0000000104b42330 main   144\n\t17  libdyld.dylib                       0x00000001b50348f0 0CB11832-70AD-3EC6-A191-AFB85E3BF348   6384\n)"

**Comment by gustavobnmx** [comment]
@pasha4uu isn't this related to #588?

I'm experiencing the same behavior on iOS 13

**Comment by wirelessmundi** [comment]
I am running into the same issue you described above.

Log:
por omisión	12:45:55.951394+0200	linphone	Apps receving VoIP pushes must post an incoming call (via CallKit or IncomingCallNotifications) in the same run loop as   pushRegistry:didReceiveIncomingPushWithPayload:forType:[withCompletionHandler:] without delay.
por omisión	12:45:55.951448+0200	linphone	*** Assertion failure in -[PKPushRegistry _terminateAppIfThereAreUnhandledVoIPPushes], /Library/Caches/com.apple.xbs/Sources/PushKit/PushKit-37/PKPushRegistry.m:343
por omisión	12:45:55.951499+0200	linphone	*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.'
*** First throw call stack:
(0x1a33c1654 0x1a30e3bcc 0x1a32c46ec 0x1a370a16c 0x1b75b7ab8 0x1a3087524 0x1a306b1fc 0x1b75b6a70 0x1a30869a8 0x1a3087524 0x1a306a6fc 0x1a333f6bc 0x1a333a590 0x1a3339ba8 0x1ad4b0344 0x1a74753e4 0x1024efb58 0x1a31c18f0)

attached crash file.


[crashlog_pushkit.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/5203260/crashlog_pushkit.txt)

Any idea? thank you

**Comment by Raviojha62** [comment]
@pasha4uu Can you please explain here? how are you getting the calls when app in background or terminated. 
I have also download the complete code and run it successfully in device but callkit is not working in the these state i think .
Please help.

**Comment by KhairulRijl** [comment]
hi, i have same issue
1. A Call want call B
2. A send invite
3. B is Offline
4. Server Send voip push notification
5. B is wakeup and online
6. B not receive call
7. state in A not change

**Comment by leelai** [comment]
We have encounter the simmiler issue, espically when we put the phone over night and test push call next morning, it couldn't received the first call but the second call works, if you know how to fix , please email us (mark@twwinhome.com and aloha.app4u@gmail.com)

**Comment by bnsy** [comment]
Is the problem solved @leelai ?

We are also facing same problem
