### ISSUE TITLE
How to remove the Camera/Video permission alert -Only audio calls SETUP

### ISSUE THREAD

**Issue by pasha4uu** [BelledonneCommunications/linphone-iphone#691]
Hi,

**Regarding the video permission alert remove ,** 
 I successfully integrated to LinPhone my existing project . in my project only had audio calls setup. so i possibility  removed chat and video related code, even though it asks  access the  camera/video permission. if i Removed from info.plist getting the crash issue that **NSCameraUsageDescription privacy sensitive data**. 

please would be any help more appreciate you.

Thank you,

**Comment by piyush-ebizz** [comment]
Give me your email ID @pasha4uu.
give me the project code to check the issue.

**Comment by Raviojha62** [comment]
Can you help me how to achieve the call kit because I am using the same code and it's not working when the app is in the background or killed state. Linphone said its supports to call kit and its testflight build is working fine, but when I am using this code on a real device I am not getting any call notification, please let me know

**Comment by pyXos** [comment]
I'd like to follow up on this issue.
Is it possible to use the SDK with audio only, i.e. without using the camera permission?

Thank you!
