### ISSUE TITLE
CallKit shows two calls with pushNotification and error on answer

### ISSUE THREAD

**Issue by mircoiplabs** [BelledonneCommunications/linphone-iphone#827]
Hello, 

I've installed the 4.6.2 release with the SDK 5.1.42.

The app is Linphone standard with no particular editing.

The issue is that when a push notification for a VoIP call arrives and the app isn't in foreground, the CallKit shows a call with "Calling" as display name (call state = "pushIncomingReceived" as I found in the CallManager->onCallStateChanged).

If I answer, the app just close the call/answer to an "Anonymous" caller, and from the caller side it looks like "Busy caller", so this is the issue.

But if I decline this call, the CallKit shows immediately a new call with the correct caller number and then if I answer it goes well.

What should I do to go well with VoIP call push notification? 

Thank you for your help.

**Comment by rayjayhero** [comment]
We are seeing the same problem exactly as described above and it doesn't matter if we follow the Flexisip instructions - we cannot get the Caller ID information to show in the initial push and then we get a 2nd "call" popping up when the INVITE itself arrives on the App which thinks for some reason there are now 2 calls in-progress.  The call-id matches in the push notification as what is in the SIP INVITE message:

https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/D.%20Specifications/Push%20notifications/

**Comment by rayjayhero** [comment]
Actually we think we have fixed this now by looking at the Flexisip source code.  The JSON payload in the push notification needs to match exactly the below format.  I think we were missing the square brackets (array) around "loc-args" value and the uuid format needs to match as well.

{
        "aps": {
                "sound": "",
                "loc-key": "%s",
                "loc-args": ["%s"],
                "call-id": "%s",
                "uuid": %s,
                "send-time": "%s"
        },
        "from-uri": "%s",
        "display-name": "%s",
        "pn_ttl": %d,
        "customPayload": %s
}

**Comment by mircoiplabs** [comment]
Thank you for your answer.

We are trying the same thing changing the push payload, this is our payload made from a PHP server in JSON format.

How is in particular your uuid format?

                                    $data = [
                                                'aps' => [

        "call-id" => caller,
        "loc-args" => [
            "sip:" . caller . '@0.0.0.0'
        ],
        "loc-key" => "IC_MSG",
        "send-time" => gmdate("Y-m-d H:i:s"),
        "sound" => "",
        "uuid" =>"<urn:uuid:123456ee-a123-1234-b8d7-c2fb12c12f12>"
    ],
    "customPayload" => [],
    "display-name" => "",
    "from-uri" => "sip:" . caller . '@0.0.0.0',
    "pn_ttl" => 50
];

So you successful show calls by changing this payload now?

**Comment by rayjayhero** [comment]
Hi there,

The call-id is your problem I think.  On IOS the call-id has to match 
exactly the 'Call-ID' header in the SIP INVITE that is sent subsequently 
to the Linphone App.  If the call-id is not matching exactly the SIP 
INVITE Call-ID header then you will have problems with the 2 separate 
calls coming into the App.

We are setting the uuid to the receiving phone number and the loc-args, 
from-uri and display-name to the calling phone number. Our query looks 
something like the following assuming an example call from 6497654321 to 
6491234567

{
     "aps": {
         "sound":"",
         "loc-key":"IC_MSG",
         "loc-args": [
             "6491234567"
         ],
         ***@***.***",
         "uuid":"6497654321",
         "send-time":"2022-06-17 12:34:56"
     },
     "from-uri":"6491234567",
     "display-name":"6491234567",
     "pn_ttl":60,
     "customPayload": {}
}

As you can see the call-id generated by your VOIP platform (e.g. 
Asterisk) needs to match exactly what is sent in the SIP INVITE message 
to the App or you will have problems with the App identifying the push 
and then the INVITE as 2 separate calls!  If you are using Asterisk as 
your VOIP platform then use the ${SIPCALLID} variable in the push 
message and the 'b' flag in the Dial command (via a sub routine) to 
retrieve the call-id of the outgoing call to the client otherwise you 
will get the wrong call-id in the dialplan (i.e. the originating call-id).

Good luck!

Thanks,
Ray

**Comment by mircoiplabs** [comment]
Hi, we were looking for matching the two call-id as you suggested, we figured it out that this is the problem at 99%, and this is exactly what we were looking for.

I'm going to try as you wrote, thank you so much for your time!

**Comment by mingeee** [comment]
Arghh! I have encountered a somewhat similar issue but with Callkit / push notification. 

My first call with push notifications will always come up as an anonymous caller. Then, when I tried to accept the call, the call would be rejected immediately without a second call. The caller will get a message saying that the "xxx is busy"

if I reject the anonymous call, then the subsequent call will work as usual.

```
body:  {
  key: '{\n' +
    '  "aps" : {\n' +
    '    "send-time" : "2024-05-10 05:33:35",\n' +
    '    "uuid" : "<urn:uuid:61f7fe4e-7526-4d1a-9c5c-cc96ba39b683>",\n' +
    '    "loc-key" : "IC_MSG",\n' +
    '    "loc-args" : [\n' +
    '      "+60379483539"\n' +
    '    ],\n' +
    '    "call-id" : "062bb315-cbbb-4e67-83c0-a7c3b89052f9",\n' +
    '    "sound" : ""\n' +
    '  },\n' +
    '  "pn_ttl" : 90,\n' +
    '  "from-uri" : "sip:+60379483539@10.168.2.10",\n' +
    '  "display-name" : "+60379483539",\n' +
    '  "customPayload" : {\n' +
    '\n' +
    '  }\n' +
    '}'
}
```

**Comment by gcareri** [comment]
Hi everyone,

Has anyone managed to resolve the issue? I continue to receive calls as "anonymous," and after about 10 seconds, the correct call information updates.

Thanks in advance to anyone who can help.

Best regards,
Giuseppe
