### ISSUE TITLE
How to get push notification payload information

### ISSUE THREAD

**Issue by mircoiplabs** [BelledonneCommunications/linphone-iphone#830]
Hello,

I updated the version of my Linphone-based app (that was quite old) and I figured it out that Linphone "hidden" PushKit in the SDK, so the way I can manage push notification has been changed.

When I debug, I see the push notification payload when received, but I don't know how to get the information I see.

It would be good if I can get the display-name from the push notification to show the caller name in the CallKit... 

Any suggestions? Thanks

**Comment by Viish** [comment]
HI @mircoiplabs,

Have you tried the new [push received callback](https://download.linphone.org/snapshots/docs/liblinphone/latest/swift/Classes/CoreDelegateStub.html#/s:10linphonesw12CoreDelegateP26onPushNotificationReceived4core7payloadyAA0B0C_SStF) I added in the Core listener?
You have to use a recent 5.2-alpha SDK to have it.

**Comment by thanhbpcvoyagerhcm** [comment]
Hi @Viish 

I'm using [onPushNotificationReceived](https://download.linphone.org/snapshots/docs/liblinphone/latest/swift/Classes/CoreDelegateStub.html#/s:10linphonesw12CoreDelegateP26onPushNotificationReceived4core7payloadyAA0B0C_SStF) to get payload PushKit. 
It returns a payload as String, and I'm trying to parse it to JSON/Dictionary but got an error because of the incorrect format

```
{
    aps =     {
        "call-id" = 1798382879;
        "loc-args" =         (
            E12SJT
        );
        "loc-key" = "IC_MSG";
        "send-time" = "2022-11-29 04:01:01";
        sound = "";
        uuid = "<urn:uuid:53e9472d-16a0-006f-9b77-034480a3bd20>";
    };
    customPayload =     {
    };
    "display-name" = E12SJT;
    "from-uri" = "sip:username@sip.linhome.org";
    "pn_ttl" = 50;
}
```

How can I get it as JSON/Dictionary like `payload.dictionaryPayload` of PKPushPayload?
