### ISSUE TITLE
Assertion failure in -[PKPushRegistry _terminateAppIfThereAreUnhandledVoIPPushes], PKPushRegistry.m

### ISSUE THREAD

**Issue by waseemkhanyes** [BelledonneCommunications/linphone-iphone#834]
@Viish hi, i'm using linphone iOS and having issue in push notification first time app receive push notification successfully and in second app crashe
<img width="1217" alt="123123" src="https://user-images.githubusercontent.com/59431339/181607151-2d7e250b-0cac-4507-ae18-2cd2b034f0ba.png">
<img width="336" alt="Screenshot at Jul 28 23-07-47" src="https://user-images.githubusercontent.com/59431339/181607283-5893b3a7-cd74-4861-9f9b-a1495934cc96.png">

as i'm using an old build and unable to resolve this and also no idea to configure latest code in my existing build...
Please help me.....
Thanks

**Comment by Viish** [comment]
Hi,
When a push is being received on iOS, you must display a notification to the user, otherwise the system will crash your app.
There is a special permission you can ask Apple for that allows you to bypass this behavior and have "silent" pushes (I don't recall how it's really called).
We have this permission as we need it to be able to silence chat rooms.
Hope it helps.
Cheers,
