### ISSUE TITLE
notify_presence_received is not getting called approprietly

### ISSUE THREAD

**Issue by nitesh-borad** [BelledonneCommunications/linphone-iphone#89]
I have implemented code for Friend Presence referring tutorial: http://www.linphone.org/docs/liblinphone/group__buddy__tutorials.html

But, notify_presence_received method is not getting called at appropriate time. Sometimes, it gets called instantly when other user gets online/offline, sometimes not. Sometime it gets called after taking very much time, sometimes never.
And it also gives only two statuses: online and offline. I never got other statuses like 'on-the-phone', 'busy', 'away' etc.

**1. Should I do anything else apart from this tutorial code?
2. At which time user gets offline status of other friend?
3. Do I need to make user online/offline manually (programatically):** `linphone_core_set_presence_model(LC, linphone_presence_model_new_with_activity(LinphonePresenceActivityOnline, NULL));`

  **OR it is already handled in linphone-sdk?**

**4. If need to do it programatically, then where can I write code to make user offline?**

I am using:
Xcode 7.3, iOS 9, Devices + Simulator, linphone-iphone (3.13.9) source code and sip.linphone.org accounts.

**Comment by bagage** [comment]
Presence is still experimental but slowly getting stable. To get status like 'on-the-phone', you must use the following:

```
m = linphone_friend_get_presence_model(friend)
a = linphone_presence_model_get_activity(m)
t = linphone_presence_activity_get_type(a) 
```

However we strongly suggest not to use peer to peer presence since this consume too much network data and drain phone batteries too much. Instead you should use presence server using rls (see `linphone_friend_list_set_rls_uri`). We started adding it in iOS and Android for long term presence, but adding short term presence does not require much more work.
