### ISSUE TITLE
setKeepAliveTimeout:handler:

### ISSUE THREAD

**Issue by reste85** [BelledonneCommunications/linphone-iphone#92]
Is there a workaround to the deprecated iOS api setKeepAliveTimeout? How can we maintain active TCP connections in background mode?

**Comment by bagage** [comment]
No, there seems no alternate yet but to use a deprecated method (we already use some of them). Cf [this SO](http://stackoverflow.com/questions/30758403/setkeepalivetimeout-is-deprecated-in-ios9) post, we already register for remote push notifications but keep alive are used too because:
* your application may not have remote push notification (server not configured)
* you may need to actively register to your SIP proxy.
So for now we'll stick with it.
